#!/bin/bash

# these files are generated by a different build script
objcode=( \
"../../logic-gate-allocator.o" \
"../../logic-gate-utility.o" \
"../../logic-gates.o" )

localsrc=( \
"gate_allocator_wrapper.cpp" \
"gate_utility_wrapper.cpp" \
"gate_wrapper.cpp" \
"logic_wrapper.cpp" )

g++ "${localsrc[@]}" "${objcode[@]}" -o ../lib/logic_wrapper.so \
-std=c++11 -shared -fPIC -llua5.3 -I../
